# Generated by Django 4.2.5 on 2023-10-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='Hayat', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='kerala', max_length=50),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
