# Generated by Django 4.2.5 on 2023-10-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0003_hotelroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='owner_number',
            field=models.IntegerField(blank=True, default=6238066012, max_length=15, null=True),
        ),
    ]
