# Generated by Django 4.2.5 on 2023-10-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0004_hotels_owner_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='owner_number',
            field=models.IntegerField(blank=True, default=6238066012, null=True),
        ),
    ]
