# Generated by Django 4.2.5 on 2023-10-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0010_alter_hotelroom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_guests',
            field=models.IntegerField(default=1),
        ),
    ]
