# Generated by Django 4.2.7 on 2023-12-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0011_reservation_num_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=4),
        ),
    ]
